readme review updates
dojo/interop pull request #26
Opened 2018-02-09 16:59 UTC by tomdye

**Type:** bug
**Type:** feature

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Readme review updates

Resolves #25

2018-02-09 17:01 UTC, tomdye commented
@agubler forgot to skip ci, sorry

2018-02-09 17:01 UTC, agubler commented on README.md
> +import ProjectorMixin from '@dojo/widget-core/mixins/Projector';
lol 😉

2018-02-09 17:02 UTC, tomdye commented on README.md
> +import ProjectorMixin from '@dojo/widget-core/mixins/Projector';
?

2018-02-13 16:56 UTC, dylans requested changes

2018-02-13 16:56 UTC, dylans commented on README.md
> +import ProjectorMixin from '@dojo/widget-core/mixins/Projector';
Could we resolve this?

2018-03-06 13:39 UTC, agubler commented on README.md
> +import ProjectorMixin from '@dojo/widget-core/mixins/Projector';
it's resolved, don't worry

2018-03-06 13:39 UTC, agubler approved these changes

2018-03-20 14:10 UTC, dylans approved these changes

2018-03-20 14:10 UTC, merged